title: Tinker CAD Studio
description: Design • Build • Think

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

search_enabled: true

url: "https://lilashiba.github.io"
baseurl: "/LilaShiba"

markdown: kramdown
highlighter: rouge

